/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 30 23:01:10 GMT 2024
 */

package com.jwetherell.algorithms.mathematics;

import org.junit.Test;
import static org.junit.Assert.*;
import com.jwetherell.algorithms.mathematics.Coprimes;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Coprimes_ESTest extends Coprimes_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      long long0 = Coprimes.getNumberOfCoprimes(1L);
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      long long0 = Coprimes.getNumberOfCoprimes(72L);
      assertEquals(24L, long0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      long long0 = Coprimes.getNumberOfCoprimes((-1534L));
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      long long0 = Coprimes.getNumberOfCoprimes(117L);
      assertEquals(72L, long0);
  }
}
