/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 30 23:04:34 GMT 2024
 */

package com.jwetherell.algorithms.mathematics;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.jwetherell.algorithms.mathematics.Distance;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Distance_ESTest extends Distance_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      double double0 = Distance.squaredDistance(933.619, (-1.0), (-643.707345), 1554.93634983268);
      assertEquals(4908896.323361702, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      long[] longArray0 = new long[2];
      longArray0[1] = (-2752L);
      long long0 = Distance.chebyshevDistance(longArray0, longArray0);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      long[] longArray0 = new long[7];
      longArray0[1] = (-1397L);
      long[] longArray1 = new long[2];
      long long0 = Distance.chebyshevDistance(longArray0, longArray1);
      assertEquals(1397L, long0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      long[] longArray0 = new long[2];
      longArray0[0] = 2013L;
      long long0 = Distance.chebyshevDistance(longArray0, longArray0);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      double double0 = Distance.squaredDistance(0L, 0L, 0L, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      double double0 = Distance.euclideanDistance(0L, 0L, 0L, 0L);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      long[] longArray0 = new long[6];
      longArray0[0] = 1066L;
      long[] longArray1 = new long[3];
      long long0 = Distance.chebyshevDistance(longArray0, longArray1);
      assertEquals(1066L, long0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      long[] longArray0 = new long[2];
      // Undeclared exception!
      try { 
        Distance.chebyshevDistance(longArray0, (long[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.jwetherell.algorithms.mathematics.Distance", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      long[] longArray0 = new long[0];
      // Undeclared exception!
      try { 
        Distance.chebyshevDistance(longArray0, longArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("com.jwetherell.algorithms.mathematics.Distance", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      double double0 = Distance.euclideanDistance((-1.0), (-52.797), 933.619, 42601.770418);
      assertEquals(42664.805569601136, double0, 0.01);
  }
}
