/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 30 23:03:16 GMT 2024
 */

package com.jwetherell.algorithms.mathematics;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.jwetherell.algorithms.mathematics.FastFourierTransform;
import com.jwetherell.algorithms.numbers.Complex;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FastFourierTransform_ESTest extends FastFourierTransform_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Complex[] complexArray0 = new Complex[4];
      Complex complex0 = Complex.polar(778.6800978, 778.6800978);
      complexArray0[0] = complex0;
      complexArray0[1] = complexArray0[0];
      complexArray0[2] = complexArray0[0];
      complexArray0[3] = complex0;
      FastFourierTransform.cooleyTukeyFFT(complexArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Complex[] complexArray0 = new Complex[6];
      // Undeclared exception!
      try { 
        FastFourierTransform.cooleyTukeyFFT(complexArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         verifyException("com.jwetherell.algorithms.mathematics.FastFourierTransform", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Complex[] complexArray0 = new Complex[0];
      FastFourierTransform.cooleyTukeyFFT(complexArray0);
      assertEquals(0, complexArray0.length);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Complex[] complexArray0 = new Complex[2];
      // Undeclared exception!
      try { 
        FastFourierTransform.cooleyTukeyFFT(complexArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.jwetherell.algorithms.numbers.Complex", e);
      }
  }
}
