/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 30 23:02:24 GMT 2024
 */

package com.jwetherell.algorithms.mathematics;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.jwetherell.algorithms.mathematics.GreatestCommonDivisor;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GreatestCommonDivisor_ESTest extends GreatestCommonDivisor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      long long0 = (-1L);
      long long1 = 4098L;
      GreatestCommonDivisor.gcdUsingRecursion((-1L), 4098L);
      long long2 = (-1344L);
      // Undeclared exception!
      GreatestCommonDivisor.gcdUsingEuclides((-1L), (-1344L));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      long long0 = 0L;
      long long1 = 0L;
      GreatestCommonDivisor.gcdUsingEuclides(0L, 0L);
      GreatestCommonDivisor.gcdUsingRecursion((-3931L), (-3931L));
      GreatestCommonDivisor greatestCommonDivisor0 = new GreatestCommonDivisor();
      long long2 = 866L;
      GreatestCommonDivisor.gcdUsingEuclides(866L, 3931L);
      GreatestCommonDivisor.gcdUsingRecursion(0L, 0L);
      GreatestCommonDivisor.gcdUsingEuclides(0L, 0L);
      GreatestCommonDivisor.gcdUsingRecursion(3573L, (-3931L));
      // Undeclared exception!
      GreatestCommonDivisor.gcdUsingEuclides((-1126L), (-2738L));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GreatestCommonDivisor.gcdUsingRecursion((-1947L), (-1947L));
      GreatestCommonDivisor.gcdUsingRecursion((-217L), (-1947L));
      GreatestCommonDivisor.gcdUsingEuclides((-1L), (-1L));
      // Undeclared exception!
      GreatestCommonDivisor.gcdUsingEuclides((-1947L), 812L);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      long long0 = (-710L);
      long long1 = (-1211L);
      // Undeclared exception!
      GreatestCommonDivisor.gcdUsingEuclides((-710L), (-1211L));
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      long long0 = (-1L);
      long long1 = 1L;
      GreatestCommonDivisor.gcdUsingRecursion((-1L), 1L);
      GreatestCommonDivisor greatestCommonDivisor0 = new GreatestCommonDivisor();
      // Undeclared exception!
      GreatestCommonDivisor.gcdUsingEuclides(0L, (-1L));
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      GreatestCommonDivisor greatestCommonDivisor0 = new GreatestCommonDivisor();
      GreatestCommonDivisor.gcdUsingRecursion((-1742L), (-1742L));
      GreatestCommonDivisor.gcdUsingEuclides(1742L, 1L);
      GreatestCommonDivisor.gcdUsingRecursion(0L, 196L);
      long long0 = 2491L;
      GreatestCommonDivisor.gcdUsingEuclides(2491L, 196L);
      long long1 = 4466L;
      GreatestCommonDivisor.gcdUsingRecursion(4466L, 1742L);
      // Undeclared exception!
      GreatestCommonDivisor.gcdUsingEuclides((-247L), (-3244L));
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      long long0 = (-584L);
      // Undeclared exception!
      GreatestCommonDivisor.gcdUsingEuclides((-487L), (-584L));
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      GreatestCommonDivisor greatestCommonDivisor0 = new GreatestCommonDivisor();
      GreatestCommonDivisor.gcdUsingRecursion(3174L, 3174L);
      GreatestCommonDivisor.gcdUsingRecursion(3174L, 3174L);
      GreatestCommonDivisor.gcdUsingRecursion(3174L, 962L);
      GreatestCommonDivisor.gcdUsingRecursion(3174L, 1L);
      GreatestCommonDivisor.gcdUsingEuclides(1L, 1L);
      GreatestCommonDivisor.gcdUsingRecursion(3174L, (-1711L));
      GreatestCommonDivisor.gcdUsingEuclides(1L, 242L);
      GreatestCommonDivisor.gcdUsingRecursion(1069L, (-1L));
      GreatestCommonDivisor.gcdUsingRecursion(1L, 1L);
      GreatestCommonDivisor.gcdUsingEuclides(1512L, 1069L);
      GreatestCommonDivisor.gcdUsingRecursion(1512L, 188L);
      GreatestCommonDivisor.gcdUsingRecursion(1L, 0L);
      GreatestCommonDivisor.gcdUsingRecursion(1308L, 215L);
      GreatestCommonDivisor.gcdUsingRecursion((-2384L), (-3594L));
      GreatestCommonDivisor.gcdUsingRecursion(215L, 1L);
      GreatestCommonDivisor.gcdUsingEuclides(3174L, 1L);
      GreatestCommonDivisor.gcdUsingRecursion((-1057L), 0L);
      GreatestCommonDivisor.gcdUsingEuclides(2309L, 1L);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      GreatestCommonDivisor greatestCommonDivisor0 = new GreatestCommonDivisor();
      GreatestCommonDivisor.gcdUsingEuclides(0L, 0L);
      GreatestCommonDivisor.gcdUsingRecursion(0L, 0L);
      GreatestCommonDivisor.gcdUsingRecursion(0L, 0L);
      // Undeclared exception!
      GreatestCommonDivisor.gcdUsingEuclides(0L, (-2292L));
  }
}
